#!/bin/sh

TARGETHOST=$1
shift
if [ "$TARGETHOST" == "--dry" ] ; then
  DRY="$TARGETHOST"
  TARGETHOST=$1
else
  DRY=$1
fi

if [ -z "$TARGETHOST" ] ; then
  echo "Usage: ./switch hostname"
  exit 1
fi

echo "Switching '$TARGETHOST'...";

if [ "$DRY" == "--dry" ] ; then
  sudo nixos-rebuild \
    --flake .#$TARGETHOST \
    --no-reexec \
    dry-build
else
  sudo nixos-rebuild \
    --flake .#$TARGETHOST \
    --no-reexec \
    switch
fi
