#!/bin/sh

TARGETHOST="$1"
shift 2>/dev/null
if [ "$TARGETHOST" == "--dry" ] ; then
  DRY="$TARGETHOST"
  TARGETHOST="$1"
else
  DRY="$1"
fi

if [ -z "$TARGETHOST" ] ; then
  echo "Usage: ./switch [--dry] <hostname>"
  exit 1
fi

echo "Switching '$TARGETHOST'..."

ROOT="$(git rev-parse --show-toplevel)"

echo "Git dir $ROOT"

if [ "$DRY" == "--dry" ] ; then
  sudo nixos-rebuild \
    --flake "$ROOT#$TARGETHOST" \
    --no-reexec \
    dry-build
else
  sudo nixos-rebuild \
    --flake "$ROOT#$TARGETHOST" \
    --no-reexec \
    switch
fi
